names<-c("reyna","jett","sova")
age<-c(20,23,30)
salary<-c(100,200,300)
df<-data.frame(names,age,salary)
cat("IQR of age is:",IQR(df $age))
cat("\nQuantile of age is:",quantile(df $age))
cat("\nRange is:",range(df $salary))